/**
 * Goan Spy JSON-LD schema deployment map (16 schemas).
 * Blueprint URLs are mapped to live Next.js routes where they differ.
 */
export const SCHEMA_DEPLOYMENT_REPORT = [
  {
    id: 1,
    schemaType: "ProfessionalService + WebSite (@graph)",
    blueprintPath: "/",
    liveRoute: "/",
    pageFile: "app/page.tsx",
  },
  {
    id: 2,
    schemaType: "AboutPage",
    blueprintPath: "/about-us/",
    liveRoute: "/about-us",
    pageFile: "app/about-us/page.tsx",
  },
  {
    id: 3,
    schemaType: "ContactPage",
    blueprintPath: "/contact-us/",
    liveRoute: "/contact-us",
    pageFile: "app/contact-us/page.tsx",
  },
  {
    id: 4,
    schemaType: "WebPage + ItemList",
    blueprintPath: "/services/",
    liveRoute: "/services",
    pageFile: "app/services/page.tsx",
  },
  {
    id: 5,
    schemaType: "Service — Infidelity Surveillance",
    blueprintPath: "/services/infidelity-investigations/",
    liveRoute: "/services/infidelity-extramarital-affairs-investigations",
    pageFile: "app/services/[slug]/page.tsx",
  },
  {
    id: 6,
    schemaType: "Service — Pre-Matrimonial Verification",
    blueprintPath: "/services/pre-matrimonial-verification/",
    liveRoute: "/services/pre-matrimonial-background-verification",
    pageFile: "app/services/[slug]/page.tsx",
  },
  {
    id: 7,
    schemaType: "Service — Child Custody Investigations",
    blueprintPath: "/services/child-custody-investigations/",
    liveRoute: "/services/child-custody-teenager-lifestyle-monitoring",
    pageFile: "app/services/[slug]/page.tsx",
  },
  {
    id: 8,
    schemaType: "Service — Missing Persons",
    blueprintPath: "/services/missing-persons-investigations/",
    liveRoute: "/services/missing-persons-investigations",
    pageFile: "app/services/[slug]/page.tsx",
  },
  {
    id: 9,
    schemaType: "Service — Corporate Due Diligence",
    blueprintPath: "/services/corporate-investigations-due-diligence/",
    liveRoute: "/services/due-diligence-investigations",
    pageFile: "app/services/[slug]/page.tsx",
  },
  {
    id: 10,
    schemaType: "Service — TSCM Bug Sweeping",
    blueprintPath: "/services/tscm-bug-sweeping/",
    liveRoute: "/services/technical-surveillance-counter-measures-tscm",
    pageFile: "app/services/[slug]/page.tsx",
  },
  {
    id: 11,
    schemaType: "PriceSpecification",
    blueprintPath: "/packages/",
    liveRoute: "/client-engagement-protocol",
    pageFile: "app/client-engagement-protocol/page.tsx",
    note: "No /packages route — pricing tiers live on the client protocol page.",
  },
  {
    id: 12,
    schemaType: "WebPage — Case Studies",
    blueprintPath: "/case-studies/",
    liveRoute: "/case-studies",
    pageFile: "app/case-studies/page.tsx",
  },
  {
    id: 13,
    schemaType: "Blog",
    blueprintPath: "/blog/",
    liveRoute: "/blog",
    pageFile: "app/blog/page.tsx",
  },
  {
    id: 14,
    schemaType: "BlogPosting — Infidelity in Goa",
    blueprintPath: "/blog/signs-infidelity-goa-vacation/",
    liveRoute: "/blog",
    pageFile: "app/blog/page.tsx",
    note: "No dedicated article route yet — embedded in blog hub @graph.",
  },
  {
    id: 15,
    schemaType: "BlogPosting — Hidden Cameras in Villas",
    blueprintPath: "/blog/hidden-camera-detection-rental-villas/",
    liveRoute: "/blog",
    pageFile: "app/blog/page.tsx",
    note: "No dedicated article route yet — embedded in blog hub @graph.",
  },
  {
    id: 16,
    schemaType: "WebPage + DigitalDocument",
    blueprintPath: "/client-protocol/",
    liveRoute: "/client-engagement-protocol",
    pageFile: "app/client-engagement-protocol/page.tsx",
  },
] as const;
